#!/usr/bin/env node
/**
 * Dotify Universal Release & Update Publisher CLI
 *
 * Usage:
 *   npm run release                                  # Bumps patch version, builds Desktop + Android, uploads to GitHub + Firestore
 *   npm run release -- minor --notes "New equalizer" # Bumps minor version with custom release notes
 *   npm run release:desktop                          # Bumps patch, builds Desktop only, publishes to GitHub + Firestore
 *   npm run release:android                          # Bumps patch, builds Android only, publishes to GitHub + Firestore
 *   npm run release:fast                             # Bumps patch, skips build (uses existing dotify.exe & dotify.apk), publishes in ~10s
 *   node scripts/release.mjs 1.2.0 --skip-build --notes "Hotfix release"
 */

import fs from 'fs';
import path from 'path';
import { execSync, spawnSync } from 'child_process';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, '..');

const GITHUB_REPO = 'Mors1A4/dotify-releases';
const FIREBASE_PROJECT_ID = 'dotify-11e01';

function parseArgs(argv) {
  const opts = {
    bumpOrVersion: 'patch',
    notes: '',
    skipBuild: false,
    desktopOnly: false,
    androidOnly: false,
    mandatory: false,
  };

  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === '--skip-build' || arg === '--fast') {
      opts.skipBuild = true;
    } else if (arg === '--desktop-only' || arg === '--desktop') {
      opts.desktopOnly = true;
    } else if (arg === '--android-only' || arg === '--android') {
      opts.androidOnly = true;
    } else if (arg === '--mandatory') {
      opts.mandatory = true;
    } else if (arg === '--current') {
      opts.bumpOrVersion = 'current';
    } else if ((arg === '--notes' || arg === '-m') && argv[i + 1]) {
      opts.notes = argv[++i];
    } else if ((arg === '--version' || arg === '-v') && argv[i + 1]) {
      opts.bumpOrVersion = argv[++i];
    } else if (!arg.startsWith('-')) {
      opts.bumpOrVersion = arg;
    }
  }
  return opts;
}

function computeNextVersion(currentVersion, bumpOrVersion) {
  const clean = currentVersion.trim().replace(/^v/i, '');
  const parts = clean.split('.').map((n) => parseInt(n, 10) || 0);
  while (parts.length < 3) parts.push(0);

  if (bumpOrVersion === 'current') return parts.join('.');
  if (bumpOrVersion === 'patch') {
    parts[2] += 1;
    return parts.join('.');
  }
  if (bumpOrVersion === 'minor') {
    parts[1] += 1;
    parts[2] = 0;
    return parts.join('.');
  }
  if (bumpOrVersion === 'major') {
    parts[0] += 1;
    parts[1] = 0;
    parts[2] = 0;
    return parts.join('.');
  }
  if (/^v?\d+\.\d+\.\d+$/.test(bumpOrVersion.trim())) {
    return bumpOrVersion.trim().replace(/^v/i, '');
  }
  throw new Error(`Invalid version argument: "${bumpOrVersion}". Expected patch, minor, major, current, or X.Y.Z`);
}

function computeAndroidVersionCode(version) {
  const [major = 1, minor = 0, patch = 0] = version.split('.').map((n) => parseInt(n, 10) || 0);
  return major * 1000000 + minor * 1000 + patch;
}

function syncVersionFiles(newVersion) {
  console.log(`\n[1/4] Syncing version v${newVersion} across Desktop & Android manifests...`);

  // 1. package.json
  const pkgPath = path.join(ROOT_DIR, 'package.json');
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
  pkg.version = newVersion;
  fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n', 'utf8');

  // 2. src-tauri/tauri.conf.json
  const tauriConfPath = path.join(ROOT_DIR, 'src-tauri', 'tauri.conf.json');
  const tauriConf = JSON.parse(fs.readFileSync(tauriConfPath, 'utf8'));
  tauriConf.version = newVersion;
  fs.writeFileSync(tauriConfPath, JSON.stringify(tauriConf, null, 2) + '\n', 'utf8');

  // 3. src-tauri/Cargo.toml
  const cargoPath = path.join(ROOT_DIR, 'src-tauri', 'Cargo.toml');
  if (fs.existsSync(cargoPath)) {
    let cargo = fs.readFileSync(cargoPath, 'utf8');
    cargo = cargo.replace(/^version\s*=\s*"[^"]*"/m, `version = "${newVersion}"`);
    fs.writeFileSync(cargoPath, cargo, 'utf8');
  }

  // 4. src/version.ts
  const versionTsPath = path.join(ROOT_DIR, 'src', 'version.ts');
  const versionTsContent = `export const APP_VERSION = '${newVersion}';\nexport const RELEASE_GITHUB_REPO = '${GITHUB_REPO}';\n`;
  fs.writeFileSync(versionTsPath, versionTsContent, 'utf8');

  // 5. src-tauri/gen/android/app/tauri.properties
  const androidPropsPath = path.join(ROOT_DIR, 'src-tauri', 'gen', 'android', 'app', 'tauri.properties');
  if (fs.existsSync(path.dirname(androidPropsPath))) {
    const versionCode = computeAndroidVersionCode(newVersion);
    const propsContent = [
      '// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.',
      `tauri.android.versionName=${newVersion}`,
      `tauri.android.versionCode=${versionCode}`,
      '',
    ].join('\n');
    fs.writeFileSync(androidPropsPath, propsContent, 'utf8');
  }
}

function getGitHubToken() {
  if (process.env.GH_TOKEN && process.env.GH_TOKEN.trim()) {
    return process.env.GH_TOKEN.trim();
  }
  if (process.env.GITHUB_TOKEN && process.env.GITHUB_TOKEN.trim()) {
    return process.env.GITHUB_TOKEN.trim();
  }
  try {
    const res = spawnSync('git', ['credential', 'fill'], {
      input: 'protocol=https\nhost=github.com\n\n',
      encoding: 'utf8',
      cwd: ROOT_DIR,
    });
    if (res.stdout) {
      const match = res.stdout.match(/^password=(.+)$/m);
      if (match && match[1]) {
        return match[1].trim();
      }
    }
  } catch {
    // ignore
  }
  return '';
}

function buildTargets(newVersion, opts) {
  if (opts.skipBuild) {
    console.log('\n[2/4] Skipping compilation (--skip-build). Using existing binaries...');
    return;
  }

  // Remove existing root binaries to guarantee only newly compiled binaries are published
  if (!opts.androidOnly) {
    try { fs.unlinkSync(path.join(ROOT_DIR, 'dotify.exe')); } catch {}
    try { fs.unlinkSync(path.join(ROOT_DIR, 'dotify-setup.exe')); } catch {}
    try { fs.unlinkSync(path.join(ROOT_DIR, 'src-tauri', 'target', 'release', 'app.exe')); } catch {}
  }
  if (!opts.desktopOnly) {
    try { fs.unlinkSync(path.join(ROOT_DIR, 'dotify.apk')); } catch {}
  }

  if (!opts.androidOnly) {
    console.log('\n[2/4] Building Windows Desktop standalone binary & NSIS installer...');
    try {
      execSync('powershell -NoProfile -Command "Stop-Process -Name app -Force -ErrorAction SilentlyContinue"', {
        cwd: ROOT_DIR,
        stdio: 'ignore',
      });
    } catch {}

    execSync('npx tauri build', { cwd: ROOT_DIR, stdio: 'inherit' });

    const builtExe = path.join(ROOT_DIR, 'src-tauri', 'target', 'release', 'app.exe');
    const rootExe = path.join(ROOT_DIR, 'dotify.exe');
    if (fs.existsSync(builtExe)) {
      fs.copyFileSync(builtExe, rootExe);
      const localAppData = process.env.LOCALAPPDATA;
      if (localAppData) {
        const installedDir = path.join(localAppData, 'dotify');
        if (fs.existsSync(installedDir)) {
          try {
            fs.copyFileSync(builtExe, path.join(installedDir, 'app.exe'));
          } catch {}
        }
      }
    }

    const nsisDir = path.join(ROOT_DIR, 'src-tauri', 'target', 'release', 'bundle', 'nsis');
    if (fs.existsSync(nsisDir)) {
      const versionedSetup = path.join(nsisDir, `dotify_${newVersion}_x64-setup.exe`);
      const rootSetup = path.join(ROOT_DIR, 'dotify-setup.exe');
      if (fs.existsSync(versionedSetup)) {
        fs.copyFileSync(versionedSetup, rootSetup);
      } else {
        const candidates = fs.readdirSync(nsisDir).filter((f) => f.endsWith('-setup.exe'));
        if (candidates.length > 0) {
          fs.copyFileSync(path.join(nsisDir, candidates[0]), rootSetup);
        }
      }
    }
  }

  if (!opts.desktopOnly) {
    console.log('\n[2/4] Building and signing Android Release APK (build-apk.bat)...');
    execSync('cmd.exe /c build-apk.bat', { cwd: ROOT_DIR, stdio: 'inherit' });
  }
}

function verifyApkVersion(apkPath, expectedVersion) {
  try {
    const aaptCandidates = [
      'C:\\Users\\monty\\AppData\\Local\\Android\\Sdk\\build-tools\\34.0.0\\aapt.exe',
      'aapt.exe',
      'aapt',
    ];
    let aaptBin = aaptCandidates.find((b) => fs.existsSync(b)) || 'aapt';
    const out = execSync(`"${aaptBin}" dump badging "${apkPath}"`, { encoding: 'utf8' });
    const match = out.match(/versionName='([^']+)'/);
    if (match && match[1]) {
      const apkVer = match[1].trim();
      if (apkVer !== expectedVersion) {
        throw new Error(
          `CRITICAL: APK version mismatch! Expected v${expectedVersion}, but ${apkPath} contains versionName='${apkVer}'. Refusing to publish stale APK!`
        );
      }
      console.log(`[VERIFIED] dotify.apk versionName='${apkVer}' matches release v${expectedVersion}`);
    }
  } catch (err) {
    if (err.message && err.message.includes('CRITICAL')) throw err;
    console.warn('[WARN] Could not run aapt verification:', err.message);
  }
}

function publishToGitHubReleases(version, notes, ghToken, opts = {}) {
  console.log(`\n[3/4] Publishing v${version} binaries to GitHub Releases (${GITHUB_REPO})...`);

  const env = { ...process.env };
  if (ghToken) {
    env.GH_TOKEN = ghToken;
  }

  const tag = `v${version}`;
  const baseDownload = `https://github.com/${GITHUB_REPO}/releases/download/${tag}`;

  const manifest = {
    version,
    notes,
    publishedAt: Date.now(),
    windowsExeUrl: `${baseDownload}/dotify.exe`,
    windowsSetupUrl: `${baseDownload}/dotify-setup.exe`,
    androidApkUrl: `${baseDownload}/dotify.apk`,
    releasePageUrl: `https://github.com/${GITHUB_REPO}/releases/tag/${tag}`,
  };

  const latestJsonPath = path.join(ROOT_DIR, 'latest.json');
  fs.writeFileSync(latestJsonPath, JSON.stringify(manifest, null, 2) + '\n', 'utf8');

  const assets = [latestJsonPath];

  if (!opts.androidOnly) {
    const exePath = path.join(ROOT_DIR, 'dotify.exe');
    const setupPath = path.join(ROOT_DIR, 'dotify-setup.exe');
    if (fs.existsSync(exePath)) assets.push(exePath);
    if (fs.existsSync(setupPath)) assets.push(setupPath);
  }

  if (!opts.desktopOnly) {
    const apkPath = path.join(ROOT_DIR, 'dotify.apk');
    if (fs.existsSync(apkPath)) {
      verifyApkVersion(apkPath, version);
      assets.push(apkPath);
    }
  }

  if (assets.length <= 1) {
    throw new Error('No release assets (dotify.exe, dotify-setup.exe, dotify.apk) found to publish.');
  }

  // Ensure repo exists
  const viewRepo = spawnSync('gh', ['repo', 'view', GITHUB_REPO], { env, cwd: ROOT_DIR, encoding: 'utf8' });
  if (viewRepo.status !== 0) {
    spawnSync(
      'gh',
      [
        'repo',
        'create',
        GITHUB_REPO,
        '--public',
        '--description',
        'Dotify Desktop and Android Release Binaries',
        '--add-readme',
      ],
      { env, cwd: ROOT_DIR, stdio: 'inherit' }
    );
  }

  // Check if release tag already exists
  const viewRelease = spawnSync('gh', ['release', 'view', tag, '--repo', GITHUB_REPO], {
    env,
    cwd: ROOT_DIR,
    encoding: 'utf8',
  });

  if (viewRelease.status === 0) {
    console.log(`Release ${tag} already exists; uploading updated assets with --clobber...`);
    const uploadRes = spawnSync(
      'gh',
      ['release', 'upload', tag, ...assets, '--clobber', '--repo', GITHUB_REPO],
      { env, cwd: ROOT_DIR, stdio: 'inherit' }
    );
    if (uploadRes.status !== 0) {
      throw new Error(`Failed to upload assets to GitHub release ${tag}`);
    }
    spawnSync(
      'gh',
      ['release', 'edit', tag, '--title', `Dotify v${version}`, '--notes', notes, '--latest', '--repo', GITHUB_REPO],
      { env, cwd: ROOT_DIR, stdio: 'inherit' }
    );
  } else {
    const createRes = spawnSync(
      'gh',
      [
        'release',
        'create',
        tag,
        ...assets,
        '--title',
        `Dotify v${version}`,
        '--notes',
        notes,
        '--latest',
        '--repo',
        GITHUB_REPO,
      ],
      { env, cwd: ROOT_DIR, stdio: 'inherit' }
    );
    if (createRes.status !== 0) {
      throw new Error(`Failed to create GitHub release ${tag}`);
    }
  }

  try {
    fs.unlinkSync(latestJsonPath);
  } catch {}

  return manifest;
}

async function publishToFirestore(manifest, mandatory) {
  console.log(`\n[4/4] Syncing live release manifest to Firestore (${FIREBASE_PROJECT_ID})...`);
  const url = `https://firestore.googleapis.com/v1/projects/${FIREBASE_PROJECT_ID}/databases/(default)/documents/app_config/release`;

  const body = {
    fields: {
      version: { stringValue: String(manifest.version) },
      notes: { stringValue: String(manifest.notes) },
      publishedAt: { integerValue: String(manifest.publishedAt) },
      windowsExeUrl: { stringValue: String(manifest.windowsExeUrl) },
      windowsSetupUrl: { stringValue: String(manifest.windowsSetupUrl) },
      androidApkUrl: { stringValue: String(manifest.androidApkUrl) },
      releasePageUrl: { stringValue: String(manifest.releasePageUrl) },
      mandatory: { booleanValue: Boolean(mandatory) },
    },
  };

  const res = await fetch(url, {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });

  if (!res.ok) {
    const errText = await res.text();
    throw new Error(`Firestore sync failed (${res.status}): ${errText}`);
  }
}

async function main() {
  const opts = parseArgs(process.argv.slice(2));
  const pkgPath = path.join(ROOT_DIR, 'package.json');
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
  const currentVersion = pkg.version || '1.0.0';
  const nextVersion = computeNextVersion(currentVersion, opts.bumpOrVersion);
  const notes =
    opts.notes.trim() ||
    `Dotify v${nextVersion} update with latest desktop & Android improvements, bug fixes, and streaming optimizations.`;

  console.log('========================================================');
  console.log(`   Dotify Release Publisher: v${currentVersion} -> v${nextVersion}`);
  console.log('========================================================');

  syncVersionFiles(nextVersion);
  buildTargets(nextVersion, opts);

  const ghToken = getGitHubToken();
  const manifest = publishToGitHubReleases(nextVersion, notes, ghToken, opts);
  await publishToFirestore(manifest, opts.mandatory);

  console.log('\n========================================================');
  console.log(`   SUCCESS! Dotify v${nextVersion} is now LIVE!`);
  console.log(`   Release Page: ${manifest.releasePageUrl}`);
  console.log(`   Windows Exe:  ${manifest.windowsExeUrl}`);
  console.log(`   Android APK:  ${manifest.androidApkUrl}`);
  console.log('========================================================\n');
}

main().catch((err) => {
  console.error('\n[RELEASE ERROR]:', err.message || err);
  process.exit(1);
});
